# Generated by Django 3.1.2 on 2020-10-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='C',
            fields=[
                ('qno', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=200)),
                ('option1', models.CharField(max_length=100, null='true')),
                ('option2', models.CharField(max_length=100, null='true')),
                ('option3', models.CharField(max_length=100, null='true')),
                ('option4', models.CharField(max_length=100, null='true')),
                ('ans', models.CharField(max_length=1, null='true')),
                ('answer', models.CharField(choices=[('1', models.CharField(max_length=100, null='true')), ('2', models.CharField(max_length=100, null='true')), ('3', models.CharField(max_length=100, null='true')), ('4', models.CharField(max_length=100, null='true'))], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Cpp',
            fields=[
                ('qno', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=200)),
                ('option1', models.CharField(max_length=100, null='true')),
                ('option2', models.CharField(max_length=100, null='true')),
                ('option3', models.CharField(max_length=100, null='true')),
                ('option4', models.CharField(max_length=100, null='true')),
                ('ans', models.CharField(max_length=1, null='true')),
                ('answer', models.CharField(choices=[('1', models.CharField(max_length=100, null='true')), ('2', models.CharField(max_length=100, null='true')), ('3', models.CharField(max_length=100, null='true')), ('4', models.CharField(max_length=100, null='true'))], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Java',
            fields=[
                ('qno', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=200)),
                ('option1', models.CharField(max_length=100, null='true')),
                ('option2', models.CharField(max_length=100, null='true')),
                ('option3', models.CharField(max_length=100, null='true')),
                ('option4', models.CharField(max_length=100, null='true')),
                ('ans', models.CharField(max_length=1, null='true')),
                ('answer', models.CharField(choices=[('1', models.CharField(max_length=100, null='true')), ('2', models.CharField(max_length=100, null='true')), ('3', models.CharField(max_length=100, null='true')), ('4', models.CharField(max_length=100, null='true'))], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('idno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=40)),
                ('intrest', models.CharField(choices=[('C', 'C'), ('C++', 'C++'), ('Java', 'Java'), ('Python', 'Python')], max_length=6)),
                ('marks', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Python',
            fields=[
                ('qno', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=200)),
                ('option1', models.CharField(max_length=100, null='true')),
                ('option2', models.CharField(max_length=100, null='true')),
                ('option3', models.CharField(max_length=100, null='true')),
                ('option4', models.CharField(max_length=100, null='true')),
                ('ans', models.CharField(max_length=1, null='true')),
                ('answer', models.CharField(choices=[('1', models.CharField(max_length=100, null='true')), ('2', models.CharField(max_length=100, null='true')), ('3', models.CharField(max_length=100, null='true')), ('4', models.CharField(max_length=100, null='true'))], max_length=1)),
            ],
        ),
    ]
