# Generated by Django 3.1.2 on 2020-10-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainprocess', '0003_auto_20201028_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='intrest',
            field=models.CharField(blank=True, choices=[('C', 'C'), ('C++', 'C++'), ('Java', 'Java'), ('Python', 'Python')], max_length=6),
        ),
    ]
