# Generated by Django 3.1.2 on 2020-10-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainprocess', '0004_auto_20201028_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpp',
            name='question',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='java',
            name='question',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='python',
            name='question',
            field=models.TextField(),
        ),
    ]
