# Generated by Django 3.1.2 on 2020-11-04 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainprocess', '0006_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='category',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
