# Generated by Django 3.1.2 on 2020-11-04 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainprocess', '0007_profile_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='category',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
