# Generated by Django 3.1.2 on 2020-11-04 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainprocess', '0008_auto_20201105_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='category',
            field=models.CharField(blank=True, choices=[('Legendary', 'Legendary'), ('Titan', 'Titan'), ('Champion', 'Champion'), ('Gold', 'Gold'), ('Silver', 'Silver'), ('Bronze', 'Bronze')], max_length=15),
        ),
    ]
