# Generated by Django 3.1.2 on 2020-11-05 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainprocess', '0012_auto_20201106_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectrequest',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='mainprocess.profile'),
        ),
        migrations.AlterField(
            model_name='connectrequest',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='mainprocess.profile'),
        ),
    ]
