# Generated by Django 3.1.2 on 2020-11-05 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainprocess', '0013_auto_20201106_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectrequest',
            name='connectlist',
            field=models.OneToOneField(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='mainprocess.profile'),
            preserve_default=False,
        ),
    ]
