# Generated by Django 3.1.2 on 2020-11-05 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainprocess', '0014_connectrequest_connectlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connectrequest',
            name='connectlist',
        ),
    ]
