# Generated by Django 3.1.2 on 2020-11-05 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainprocess', '0016_connectrequest_connectlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connectrequest',
            name='connectlist',
        ),
        migrations.AddField(
            model_name='connectrequest',
            name='connectlist',
            field=models.ManyToManyField(blank=True, default=None, to='mainprocess.Profile'),
        ),
    ]
