# Generated by Django 3.1.2 on 2020-11-05 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainprocess', '0017_auto_20201106_0322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connectrequest',
            name='connectlist',
        ),
    ]
