# Generated by Django 3.1.7 on 2021-04-04 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainprocess', '0019_auto_20201106_0512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('mno', models.AutoField(primary_key=True, serialize=False)),
                ('read', models.BooleanField(default=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Mreceiver', to='mainprocess.profile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Msender', to='mainprocess.profile')),
            ],
        ),
    ]
