# Generated by Django 3.1.7 on 2021-04-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainprocess', '0020_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message',
            field=models.CharField(max_length=2000, null='true'),
            preserve_default='true',
        ),
    ]
