# Generated by Django 3.1.7 on 2021-04-04 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainprocess', '0021_message_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='receiver',
            new_name='Mreceiver',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='sender',
            new_name='Msender',
        ),
    ]
