# Generated by Django 3.1.7 on 2021-04-04 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainprocess', '0022_auto_20210404_2335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='Mreceiver',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='Msender',
            new_name='sender',
        ),
    ]
