# Generated by Django 3.1.7 on 2021-04-04 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainprocess', '0023_auto_20210404_2341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='mess',
        ),
    ]
