# Generated by Django 3.1.7 on 2021-04-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainprocess', '0024_auto_20210404_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c',
            name='answer',
            field=models.CharField(choices=[('1', models.CharField(max_length=10000, null='true')), ('2', models.CharField(max_length=10000, null='true')), ('3', models.CharField(max_length=10000, null='true')), ('4', models.CharField(max_length=10000, null='true'))], max_length=1),
        ),
        migrations.AlterField(
            model_name='c',
            name='option1',
            field=models.CharField(max_length=10000, null='true'),
        ),
        migrations.AlterField(
            model_name='c',
            name='option2',
            field=models.CharField(max_length=10000, null='true'),
        ),
        migrations.AlterField(
            model_name='c',
            name='option3',
            field=models.CharField(max_length=10000, null='true'),
        ),
        migrations.AlterField(
            model_name='c',
            name='option4',
            field=models.CharField(max_length=10000, null='true'),
        ),
    ]
